from Ramble.Model.model_ramble import Ramble, RambleDetail

standard = {"Equipements":
                    ["sac à dos 20-30 Litres", "Boussole + Carte (1/25000 ou au 1/50000)",
                    "Chaussures (imperméables et respirantes)",
                    "Pantalon léger",
                    "Chaussettes hautes"
                    "Téléphone portable",
                    "Appareil photos + piles de rechange éventuellement",
                    "Mouchoir",
                    "T-shirt",
                    "Veste polaire",
                    "Identité et Assurance"],
            "Alimentations": ["Eau",
                             "Pique-nique"]
            }


experimente = {"Equipements": [
                            "Sac à dos 55 litres minimum",
                            "Housse de pluie",
                            "Réchaud",
                            "Briquet",
                            "Couverture de survie",
                            "Boussole",
                            "Carte (1/25000 ou au 1/50000)",
                            "Bonnet",
                            "Veste polaire",
                            "Gants",
                            "Baton de randonnée",
                            "Créme solaire",
                            "Lunette de soleil",
                            "Casquette",
                            "Mini-pharmacie",
                            "Papier toilette",
                            "mouchoir",
                            "Sacs poubelle",
                            "Siflet",
                            "Appareil photos + piles de rechange éventuellement",
                            "Identité et Assurance"],
               "Alimentations": ["Eau",
                                 "Gourde",
                                 "Barre de céréales",
                                 "Fruits secs",
                                 "Pâte d'amande"]
           }

experimente_nuit = {"Equipements": ["Sac à dos 55 litres minimum",
                            "Housse de pluie",
                            "Tente",
                            "Matelas auto-gonflant",
                            "Sac de couchage",
                            "Réchaud",
                            "Briquet",
                            "Couverture de survie",
                            "Boussole",
                            "Carte (1/25000 ou au 1/50000)",
                            "Bonnet",
                            "Veste polaire",
                            "Gants",
                            "Baton de randonnée",
                            "Créme solaire",
                            "Lunette de soleil",
                            "Casquette",
                            "Mini-pharmacie",
                            "Papier toilette",
                            "mouchoir",
                            "Sacs poubelle",
                            "Siflet",
                            "Appareil photos + piles de rechange éventuellement",
                            "Identité et Assurance"],
               "Alimentations": ["Eau",
                                 "Gourde",
                                 "Barre de céréales",
                                 "Fruits secs",
                                 "Pâte d'amande"]
           }