# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from docker Hub as your build environment.
image: python:3.5.1

pipelines:
  branches:
      master:
       - step:
           name: Deploy to Heroku
           deployment: production   # set to test, staging or production
           script:
              - git push https://heroku:$API_KEY_HEROKU@git.heroku.com/$APP_NAME.git HEAD
      development:
       - step:
          name: Test unitaire
          image: python:3.7.2
          deployment: Test
          script:
            - echo $FALSK_CONFIG
            - pip install -r requirements.txt
            - python -m pytest -ra -p no:cacheprovider tests
       - step:
          name: Deploy to Heroku
          deployment: production   # set to test, staging or production
          script:
            - git push https://heroku:$API_KEY_HEROKU@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
       - step:
          name: Testing fonctional
          image:
            name: postman/newman_alpine33
          script:
            - newman --version
            - newman run https://api.getpostman.com/collections/4960060-ac18f48c-2248-446e-a086-ffea7b21e9a7?apikey=6963ee6206c34b57be506708dfa611e8