version: '3.7'

services:
  postgres:
    build: docker/postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql
    env_file: docker/postgres/postgres.env
    ports:
      - "5432:5432"

  flask:
    restart: always
    build: docker/flask
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    expose:
      - 8000
    depends_on:
      - migration
    links:
      - postgres
    volumes:
      - .:/app
    env_file: docker/flask/flask.env

  migration:
    build: docker/flask
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    expose:
      - 8000
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/app
    env_file: docker/flask/flask.env
    command: >
      sh -c "python manager.py db upgrade &&
             python manager.py db migrate"
  nginx:
    build: docker/nginx
    restart: always
    volumes:
      - /www/static
    ports:
      - 80:80
    depends_on:
      - flask

  test_unitaire:
    build: docker/flask
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      OAUTHLIB_INSECURE_TRANSPORT: 1
      OAUTHLIB_RELAX_TOKEN_SCOPE: 1
    volumes:
      - .:/app
    env_file: docker/flask/flask.env
    depends_on:
      - nginx
    command: python -m pytest -ra -p no:cacheprovider tests/unitaire
    tty: true
