"""empty message

Revision ID: 144325c07993
Revises: eae63df1280a
Create Date: 2019-11-28 12:21:12.148086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144325c07993'
down_revision = 'eae63df1280a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ramble_tag_association')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tags_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ramble_tag_association',
    sa.Column('ramble_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ramble_id'], ['tags.id'], name='ramble_tag_association_ramble_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['rambles.id'], name='ramble_tag_association_tag_id_fkey')
    )
    # ### end Alembic commands ###
