"""empty message

Revision ID: 1cd0431457e4
Revises: 2997edf8a0de
Create Date: 2019-09-06 12:52:00.726815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd0431457e4'
down_revision = '2997edf8a0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_reset_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_reset_password', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
