"""empty message

Revision ID: 26d5202f9253
Revises: 144325c07993
Create Date: 2019-11-28 12:26:26.199963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d5202f9253'
down_revision = '144325c07993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ramble_tag_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ramble_tag_association',
    sa.Column('ramble_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ramble_id'], ['tags.id'], name='ramble_tag_association_ramble_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['rambles.id'], name='ramble_tag_association_tag_id_fkey')
    )
    # ### end Alembic commands ###
