"""empty message

Revision ID: 450b75595330
Revises: 
Create Date: 2019-04-29 23:44:31.477410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450b75595330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('mail', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rambles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('date_ramble', sa.DateTime(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('travel_time', sa.Float(), nullable=True),
    sa.Column('step_number', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('point_pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['interest_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ramble_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ramble_id', sa.Integer(), nullable=True),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], ['interest_points.id'], ),
    sa.ForeignKeyConstraint(['ramble_id'], ['rambles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ramble_details')
    op.drop_table('point_pictures')
    op.drop_table('user_pictures')
    op.drop_table('rambles')
    op.drop_table('interest_points')
    op.drop_table('users')
    # ### end Alembic commands ###
