"""empty message

Revision ID: 484adb7e9087
Revises: 900967d1545c
Create Date: 2019-04-30 00:05:02.775320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484adb7e9087'
down_revision = '900967d1545c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_points', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interest_points', 'username')
    # ### end Alembic commands ###
