"""empty message

Revision ID: 614f1e47fcea
Revises: 6e9d6a06f118
Create Date: 2019-07-07 12:59:02.479506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '614f1e47fcea'
down_revision = '6e9d6a06f118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_token', table_name='users')
    op.drop_column('users', 'token_expiration')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_users_token', 'users', ['token'], unique=True)
    # ### end Alembic commands ###
