"""empty message

Revision ID: 7d51c4c1cae5
Revises: 97c3afd04fe6
Create Date: 2018-03-21 09:56:54.883971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d51c4c1cae5'
down_revision = '97c3afd04fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interestPoint', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interestPoint', 'type')
    # ### end Alembic commands ###
