"""empty message

Revision ID: 900967d1545c
Revises: 450b75595330
Create Date: 2019-04-30 00:00:15.990746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900967d1545c'
down_revision = '450b75595330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interest_points', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_points', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
