"""empty message

Revision ID: 97c3afd04fe6
Revises: 0de7892288b9
Create Date: 2018-03-20 19:24:32.914621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c3afd04fe6'
down_revision = '0de7892288b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imageUrls', sa.Column('poiName', sa.String(), nullable=True))
    op.drop_column('imageUrls', 'poiId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imageUrls', sa.Column('poiId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('imageUrls', 'poiName')
    # ### end Alembic commands ###
