"""empty message

Revision ID: b623d18b7a77
Revises: 1cd0431457e4
Create Date: 2019-09-06 12:52:21.981310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b623d18b7a77'
down_revision = '1cd0431457e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_reset_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_reset_password')
    # ### end Alembic commands ###
