"""empty message

Revision ID: d446a91ee007
Revises: c6c92cbd1c0f
Create Date: 2019-07-01 17:51:42.817633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd446a91ee007'
down_revision = 'c6c92cbd1c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interest_points', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interest_points', 'visible')
    # ### end Alembic commands ###
