"""empty message

Revision ID: e1e2e6b339ce
Revises: 56310b5f7fd0
Create Date: 2019-11-25 19:40:22.683714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e2e6b339ce'
down_revision = '56310b5f7fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('derniere_connexion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'derniere_connexion')
    # ### end Alembic commands ###
